### ISSUE TITLE
cant run on vercel

### ISSUE THREAD

**Issue by MohammadTaseenKhan** [andreaskeller/rss-reader#1]
@andreaskeller 
showing this error

```bash
[23:15:52.677] Running build in Cleveland, USA (East) – cle1
[23:15:52.743] Cloning github.com/MohammadTaseenKhan/developers-feed (Branch: main, Commit: bcc2b14)
[23:15:52.749] Skipping build cache, deployment was triggered without cache.
[23:15:53.233] Cloning completed: 489.856ms
[23:15:53.354] Running "vercel build"
[23:15:53.871] Vercel CLI 29.3.6
[23:15:54.100] Installing dependencies...
[23:15:54.395] yarn install v1.22.17
[23:15:54.426] info No lockfile found.
[23:15:54.431] [1/4] Resolving packages...
[23:15:57.384] [2/4] Fetching packages...
[23:16:11.434] [3/4] Linking dependencies...
[23:16:11.435] warning " > next@13.4.4" has incorrect peer dependency "react@^18.2.0".
[23:16:11.435] warning " > next@13.4.4" has incorrect peer dependency "react-dom@^18.2.0".
[23:16:18.090] [4/4] Building fresh packages...
[23:16:18.105] success Saved lockfile.
[23:16:18.109] Done in 23.72s.
[23:16:18.137] Detected Next.js version: 13.4.4
[23:16:18.138] Running "yarn run build"
[23:16:18.345] yarn run v1.22.17
[23:16:18.378] $ next build
[23:16:18.818] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[23:16:18.818] This information is used to shape Next.js' roadmap and prioritize features.
[23:16:18.819] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[23:16:18.819] https://nextjs.org/telemetry
[23:16:18.819] 
[23:16:18.915] - info Linting and checking validity of types...
[23:16:19.073] - info Creating an optimized production build...
[23:16:19.144] 
[23:16:19.144] > Build error occurred
[23:16:19.146] Error: Next.js requires react >= 18.2.0 to be installed.
[23:16:19.146]     at Object.<anonymous> (/vercel/path0/node_modules/next/dist/build/webpack-config.js:143:11)
[23:16:19.146]     at Module._compile (node:internal/modules/cjs/loader:1254:14)
[23:16:19.147]     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
[23:16:19.147]     at Module.load (node:internal/modules/cjs/loader:1117:32)
[23:16:19.147]     at Module._load (node:internal/modules/cjs/loader:958:12)
[23:16:19.147]     at Module.require (node:internal/modules/cjs/loader:1141:19)
[23:16:19.147]     at require (node:internal/modules/cjs/helpers:110:18)
[23:16:19.147]     at Object.<anonymous> (/vercel/path0/node_modules/next/dist/build/webpack-build/impl.js:29:64)
[23:16:19.147]     at Module._compile (node:internal/modules/cjs/loader:1254:14)
[23:16:19.147]     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
[23:16:19.255] error Command failed with exit code 1.
[23:16:19.256] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[23:16:19.287] Error: Command "yarn run build" exited with 1
[23:16:19.507] BUILD_UTILS_SPAWN_1: Command "yarn run build" exited with 1
```

**Comment by MohammadTaseenKhan** [comment]
@andreaskeller please 🥺 help 🐈

**Comment by jvkrakowski** [comment]
You need to update your dependencies. This repository was built with an older version of nextjs. They're migrating away into the App Router now, and that is what vercel is expecting. You need to adapt this to the latest nextjs release to make it work.

"
[23:16:11.435] warning " > next@13.4.4" has incorrect peer dependency "react@^18.2.0".
[23:16:11.435] warning " > next@13.4.4" has incorrect peer dependency "react-dom@^18.2.0".
"

and 

"
[23:16:19.144] > Build error occurred
[23:16:19.146] Error: Next.js requires react >= 18.2.0 to be installed.
"

I'm not sure anyone is actually updating this repository anymore.

**Comment by MohammadTaseenKhan** [comment]
after updating still showing the same error

```
[18:06:32.762] Running build in Cleveland, USA (East) – cle1
[18:06:32.822] Cloning github.com/MohammadTaseenKhan/rss-reader (Branch: main, Commit: 08b3379)
[18:06:32.827] Skipping build cache, deployment was triggered without cache.
[18:06:33.238] Cloning completed: 415.826ms
[18:06:33.545] Running "vercel build"
[18:06:34.012] Vercel CLI 31.2.2
[18:06:34.215] Installing dependencies...
[18:06:34.473] yarn install v1.22.17
[18:06:34.497] info No lockfile found.
[18:06:34.501] [1/4] Resolving packages...
[18:06:37.010] [2/4] Fetching packages...
[18:06:46.869] [3/4] Linking dependencies...
[18:06:46.870] warning " > @tailwindcss/jit@0.1.18" has incorrect peer dependency "tailwindcss@^2.0.3".
[18:06:52.683] [4/4] Building fresh packages...
[18:06:52.691] success Saved lockfile.
[18:06:52.695] Done in 18.23s.
[18:06:52.723] Detected Next.js version: 13.4.12
[18:06:52.725] Running "yarn run build"
[18:06:52.891] yarn run v1.22.17
[18:06:52.919] $ next build
[18:06:53.486] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[18:06:53.487] This information is used to shape Next.js' roadmap and prioritize features.
[18:06:53.487] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[18:06:53.487] https://nextjs.org/telemetry
[18:06:53.487] 
[18:06:53.607] - info Linting and checking validity of types...
[18:06:53.722] - info Creating an optimized production build...
[18:06:58.645] Failed to compile.
[18:06:58.645] 
[18:06:58.646] ./styles/globals.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[1].oneOf[13].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[1].oneOf[13].use[2]!./styles/globals.css
[18:06:58.646] Error: Cannot find module 'tailwindcss/lib/plugins/preflight'
[18:06:58.646] Require stack:
[18:06:58.646] - /vercel/path0/node_modules/@tailwindcss/jit/src/corePlugins/preflight.js
[18:06:58.646] - /vercel/path0/node_modules/@tailwindcss/jit/src/corePlugins/index.js
[18:06:58.646] - /vercel/path0/node_modules/@tailwindcss/jit/src/lib/setupContext.js
[18:06:58.646] - /vercel/path0/node_modules/@tailwindcss/jit/src/index.js
[18:06:58.646] - /vercel/path0/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js
[18:06:58.646] - /vercel/path0/node_modules/next/dist/build/webpack/config/blocks/css/index.js
[18:06:58.646] - /vercel/path0/node_modules/next/dist/build/webpack/config/index.js
[18:06:58.646] - /vercel/path0/node_modules/next/dist/build/webpack-config.js
[18:06:58.647] - /vercel/path0/node_modules/next/dist/build/webpack-build/impl.js
[18:06:58.647] - /vercel/path0/node_modules/next/dist/build/webpack-build/index.js
[18:06:58.647] - /vercel/path0/node_modules/next/dist/build/index.js
[18:06:58.647] - /vercel/path0/node_modules/next/dist/cli/next-build.js
[18:06:58.648] - /vercel/path0/node_modules/next/dist/lib/commands.js
[18:06:58.648] - /vercel/path0/node_modules/next/dist/bin/next
[18:06:58.648]     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
[18:06:58.648]     at /vercel/path0/node_modules/next/dist/server/require-hook.js:113:36
[18:06:58.648]     at Module._load (node:internal/modules/cjs/loader:922:27)
[18:06:58.648]     at Module.require (node:internal/modules/cjs/loader:1143:19)
[18:06:58.648]     at require (node:internal/modules/cjs/helpers:110:18)
[18:06:58.648]     at Object.<anonymous> (/vercel/path0/node_modules/@tailwindcss/jit/src/corePlugins/preflight.js:1:19)
[18:06:58.648]     at Module._compile (node:internal/modules/cjs/loader:1256:14)
[18:06:58.648]     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
[18:06:58.648]     at Module.load (node:internal/modules/cjs/loader:1119:32)
[18:06:58.648]     at Module._load (node:internal/modules/cjs/loader:960:12)
[18:06:58.648] 
[18:06:58.648] Import trace for requested module:
[18:06:58.649] ./styles/globals.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[1].oneOf[13].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[1].oneOf[13].use[2]!./styles/globals.css
[18:06:58.649] ./styles/globals.css
[18:06:58.649] 
[18:06:58.649] ./styles/globals.css
[18:06:58.649] Error: Cannot find module 'tailwindcss/lib/plugins/preflight'
[18:06:58.649] Require stack:
[18:06:58.649] - /vercel/path0/node_modules/@tailwindcss/jit/src/corePlugins/preflight.js
[18:06:58.649] - /vercel/path0/node_modules/@tailwindcss/jit/src/corePlugins/index.js
[18:06:58.649] - /vercel/path0/node_modules/@tailwindcss/jit/src/lib/setupContext.js
[18:06:58.649] - /vercel/path0/node_modules/@tailwindcss/jit/src/index.js
[18:06:58.649] - /vercel/path0/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js
[18:06:58.649] - /vercel/path0/node_modules/next/dist/build/webpack/config/blocks/css/index.js
[18:06:58.649] - /vercel/path0/node_modules/next/dist/build/webpack/config/index.js
[18:06:58.649] - /vercel/path0/node_modules/next/dist/build/webpack-config.js
[18:06:58.649] - /vercel/path0/node_modules/next/dist/build/webpack-build/impl.js
[18:06:58.650] - /vercel/path0/node_modules/next/dist/build/webpack-build/index.js
[18:06:58.650] - /vercel/path0/node_modules/next/dist/build/index.js
[18:06:58.655] - /vercel/path0/node_modules/next/dist/cli/next-build.js
[18:06:58.655] - /vercel/path0/node_modules/next/dist/lib/commands.js
[18:06:58.655] - /vercel/path0/node_modules/next/dist/bin/next
[18:06:58.655]     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
[18:06:58.655]     at /vercel/path0/node_modules/next/dist/server/require-hook.js:113:36
[18:06:58.655]     at Module._load (node:internal/modules/cjs/loader:922:27)
[18:06:58.655]     at Module.require (node:internal/modules/cjs/loader:1143:19)
[18:06:58.655]     at require (node:internal/modules/cjs/helpers:110:18)
[18:06:58.655]     at Object.<anonymous> (/vercel/path0/node_modules/@tailwindcss/jit/src/corePlugins/preflight.js:1:19)
[18:06:58.655]     at Module._compile (node:internal/modules/cjs/loader:1256:14)
[18:06:58.655]     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
[18:06:58.655]     at Module.load (node:internal/modules/cjs/loader:1119:32)
[18:06:58.655]     at Module._load (node:internal/modules/cjs/loader:960:12)
[18:06:58.655]     at tryRunOrWebpackError (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:28:311493)
[18:06:58.655]     at __webpack_require_module__ (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:28:131117)
[18:06:58.655]     at __nested_webpack_require_153754__ (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:28:130556)
[18:06:58.655]     at /vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:28:131409
[18:06:58.655]     at symbolIterator (/vercel/path0/node_modules/next/dist/compiled/neo-async/async.js:1:14444)
[18:06:58.655]     at done (/vercel/path0/node_modules/next/dist/compiled/neo-async/async.js:1:14824)
[18:06:58.656]     at Hook.eval [as callAsync] (eval at create (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:13:28867), <anonymous>:15:1)
[18:06:58.656]     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:13:26021)
[18:06:58.656]     at /vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:28:130276
[18:06:58.656]     at symbolIterator (/vercel/path0/node_modules/next/dist/compiled/neo-async/async.js:1:14402)
[18:06:58.656] -- inner error --
[18:06:58.656] Error: Cannot find module 'tailwindcss/lib/plugins/preflight'
[18:06:58.656] Require stack:
[18:06:58.656] - /vercel/path0/node_modules/@tailwindcss/jit/src/corePlugins/preflight.js
[18:06:58.656] - /vercel/path0/node_modules/@tailwindcss/jit/src/corePlugins/index.js
[18:06:58.656] - /vercel/path0/node_modules/@tailwindcss/jit/src/lib/setupContext.js
[18:06:58.656] - /vercel/path0/node_modules/@tailwindcss/jit/src/index.js
[18:06:58.656] - /vercel/path0/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js
[18:06:58.656] - /vercel/path0/node_modules/next/dist/build/webpack/config/blocks/css/index.js
[18:06:58.656] - /vercel/path0/node_modules/next/dist/build/webpack/config/index.js
[18:06:58.656] - /vercel/path0/node_modules/next/dist/build/webpack-config.js
[18:06:58.656] - /vercel/path0/node_modules/next/dist/build/webpack-build/impl.js
[18:06:58.656] - /vercel/path0/node_modules/next/dist/build/webpack-build/index.js
[18:06:58.656] - /vercel/path0/node_modules/next/dist/build/index.js
[18:06:58.656] - /vercel/path0/node_modules/next/dist/cli/next-build.js
[18:06:58.656] - /vercel/path0/node_modules/next/dist/lib/commands.js
[18:06:58.656] - /vercel/path0/node_modules/next/dist/bin/next
[18:06:58.656]     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
[18:06:58.656]     at /vercel/path0/node_modules/next/dist/server/require-hook.js:113:36
[18:06:58.656]     at Module._load (node:internal/modules/cjs/loader:922:27)
[18:06:58.656]     at Module.require (node:internal/modules/cjs/loader:1143:19)
[18:06:58.656]     at require (node:internal/modules/cjs/helpers:110:18)
[18:06:58.656]     at Object.<anonymous> (/vercel/path0/node_modules/@tailwindcss/jit/src/corePlugins/preflight.js:1:19)
[18:06:58.656]     at Module._compile (node:internal/modules/cjs/loader:1256:14)
[18:06:58.656]     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
[18:06:58.656]     at Module.load (node:internal/modules/cjs/loader:1119:32)
[18:06:58.656]     at Module._load (node:internal/modules/cjs/loader:960:12)
[18:06:58.657]     at Object.<anonymous> (/vercel/path0/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[1].oneOf[13].use[1]!/vercel/path0/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[1].oneOf[13].use[2]!/vercel/path0/styles/globals.css:1:7)
[18:06:58.657]     at /vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:28:915095
[18:06:58.657]     at Hook.eval [as call] (eval at create (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:13:28645), <anonymous>:7:1)
[18:06:58.657]     at Hook.CALL_DELEGATE [as _call] (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:13:25915)
[18:06:58.657]     at /vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:28:131150
[18:06:58.657]     at tryRunOrWebpackError (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:28:311447)
[18:06:58.657]     at __webpack_require_module__ (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:28:131117)
[18:06:58.657]     at __nested_webpack_require_153754__ (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:28:130556)
[18:06:58.657]     at /vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:28:131409
[18:06:58.657]     at symbolIterator (/vercel/path0/node_modules/next/dist/compiled/neo-async/async.js:1:14444)
[18:06:58.657] 
[18:06:58.657] Generated code for /vercel/path0/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[1].oneOf[13].use[1]!/vercel/path0/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[1].oneOf[13].use[2]!/vercel/path0/styles/globals.css
[18:06:58.657] 
[18:06:58.657] Import trace for requested module:
[18:06:58.657] ./styles/globals.css
[18:06:58.657] 
[18:06:58.658] 
[18:06:58.658] > Build failed because of webpack errors
[18:06:58.672] error Command failed with exit code 1.
[18:06:58.672] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[18:06:58.835] Error: Command "yarn run build" exited with 1
```
